# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prke < Formula
  desc "PromptKeeper CLI (prke)."
  homepage "https://promptkeeper.com"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AI-Prompt-Keeper/promptkeeper/releases/download/v0.0.4/prkedarwin_amd64.tar.gz"
      sha256 "ebc296a58d8b22841eb81bf53f2754a9d23149dc6cd7087c20e1c2f43ebe3f92"

      define_method(:install) do
        bin.install "prke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AI-Prompt-Keeper/promptkeeper/releases/download/v0.0.4/prkedarwin_arm64.tar.gz"
      sha256 "48ba6ea05b3405b159c19d1940c918843a75a1263128a5f5d85bcb505e256355"

      define_method(:install) do
        bin.install "prke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AI-Prompt-Keeper/promptkeeper/releases/download/v0.0.4/prkelinux_amd64.tar.gz"
      sha256 "59becd07f50db1fe70aad26acf20ccc5cba3794ad1fc5ad629058cfaf89fd82a"
      define_method(:install) do
        bin.install "prke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AI-Prompt-Keeper/promptkeeper/releases/download/v0.0.4/prkelinux_arm64.tar.gz"
      sha256 "15e7bf21c7451652d8e9d6fd0bc3e352ac6b880bfc9e3d3f3d6ae3f424d30037"
      define_method(:install) do
        bin.install "prke"
      end
    end
  end
end
